version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7-jammy
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: merndb
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/merndb
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mern-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    networks:
      - mern-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mern-network

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge
